name: FeroxCore
version: 1.2
author: Wqrld
main: net.wqrld.Ferox.Main
api-version: 1.8
depend: ['PlaceholderAPI', 'Multiverse-Core']
commands:
   join:
      description: joins
      usage: /join
   pastemap:
      description: paste
      usage: /pastemap
   debugmap:
      description: debug
      usage: /debugmap
   skipmap:
      description: skip
      usage: /skipmap
   stats:
      description: stats
      usage: /stats
   clearmap:
      description: clearmap
      usage: /clearmap